### ISSUE TITLE
Can’t find unpaused media elements on some pages

### ISSUE THREAD

**Issue by Mihonarium** [AudDMusic/firefox-extension#11]
Users report that on some websites, the extension doesn’t start recording audio because it can’t find any unpaused media elements

**Comment by Mihonarium** [comment]
Should be fixed on most websites. On some (such as Reddit) seems impossible to fix due to isolation?

**Comment by FoxRefire** [comment]
Already know.

This is because the audio source was changed to https://radio.garden/api/ara/content/listen/* in a recent Radio Garden specification change.

This `new URL(elem.currentSrc).origin` matches `document.location.origin`.

However, the API actually redirects to the actual source at a different origin.

This is because the extension has misidentified it as a non-CORS source and is trying to start recording directly in the content script, so it fails.

Therefore, it is necessary to change to a more reliable method of determining if it is a CORS source than making a HEAD request and checking its response.type value.

I will fix this again in my spare time.

**Comment by FoxRefire** [comment]
A bit of advice,instead of instructing the AI to fix multiple problems at once, it should be instructed to subdivide the task into smaller pieces.
At least headless elements and CORS are completely different issues.
As far as CORS is concerned, the process of detecting CORS sources should be separated from the recording process in background scripts.

**Comment by FoxRefire** [comment]
It is working, but the code is very difficult to understand and it is recommended that it be refactored in its entirety in the future.
With significant refactoring, the content script code can be reduced to just 90 lines or less, and can consist of four clear-purpose functions.


By the way, the background scripts that were removed in v3.2.3 also still have the previous code in them, so Twitch, for example, now displays a message asking for payment again, is this intended?
I've read the replies to the review of your add-on, and it seems to claim that it is a completely free add-on.
If this is not the intention, then it is obvious where it should be removed.

**Comment by Mihonarium** [comment]
That makes sense, but probably won't be a priority.

Not sure which change in 3.2.3 you mean.

We've experienced abuse by users on Twitch (on the order of $200-300 per month in server costs), so the extension basically disables itself on Twitch if an API token is not provided. The message could be clearer on the reasons, but since it is essentially a paid feature (even if for reasons separate from us wanting money from the users), we've put "Some features may require payment" on the extension page to not mislead any users.
